## YouTube Downloader API Configuration
#### API-INFO
api_title : Din-YT-Video-API
# আপনার API এর নাম

api_description : docs/DESCRIPTION.md
# API ডেসক্রিপশন ফাইলের পাথ

api_terms_of_service : http://localhost:8000/terms-of-service
# ব্যবহারের শর্তাবলী লিঙ্ক

contact_name : Din Alamin
# আপনার নাম

contact_email : user@localhost.dev
# আপনার ইমেইল

contact_url : http://localhost:8000/user

frontend_dir: frontend
# আমরা যে ফোল্ডারে index.html রেখেছি তার নাম

### API CONFIGURATIONS ###########
database_engine : sqlite:///db.sqlite3
# ডাটাবেস সেটিংস

po_token : 
visitorData : 
# ইউটিউব ব্লক এড়াতে এই দুটি মান পরে বসিয়ে নিতে পারেন

cookiefile : 
# ব্রাউজার কুকিজ ফাইল থাকলে তার পাথ

proxy : 
# যদি প্রক্সি ব্যবহার করতে চান

filename_prefix : 
# ফাইলের নামের শুরুতে কিছু যোগ করতে চাইলে

working_directory : static
# ডাউনলোড হওয়া ভিডিওগুলো এই ফোল্ডারে জমা হবে

clear_temps : true
# কাজ শেষ হলে অস্থায়ী ফাইল মুছে ফেলবে

search_limit : 50
# সার্চ রেজাল্ট লিমিট

default_extension : mp4
# ডিফল্ট ভিডিও ফরম্যাট (mp4 সাধারণত সব ডিভাইসে চলে)

enable_logging : false

### STATIC SERVER CONFIGS ####
static_server_url : 
# আলাদা স্ট্যাটিক সার্ভার থাকলে তার ইউআরএল

serve_frontend_from_static_server: false

api_base_url : http://localhost:8000
# আপনার এপিআই এর মেইন ইউআরএল

#### DOWNLOAD OPTIONS ####
default_audio_format : m4a
# অডিও ফরম্যাট সেটিংস

video_info_cache_period_in_hrs : 4
# ভিডিওর তথ্য কতক্ষণ ক্যাশে থাকবে

http_chunk_size : 4096
# ডাউনলোডের স্পিড বাড়াতে চাঙ্ক সাইজ বাড়ানো হয়েছে

concurrent_fragment_downloads : 5
# একসাথে কয়টি ফ্র্যাগমেন্ট ডাউনলোড হবে (স্পিড বাড়াবে)

retries : 10
# এরর আসলে ১০ বার ট্রাই করবে

continuedl : true
# মাঝপথে কেটে গেলে আবার সেখান থেকে শুরু হবে

noprogress : false
updatetime : false
verbose : false
quiet : true

allow_multiple_video_streams : false
allow_multiple_audio_streams : false
geo_bypass : true

# POST-DOWNLOAD OPTIONS
embed_subtitles : true
# ভিডিওতে সাবটাইটেল যুক্ত করবে (যদি থাকে)

append_id_in_filename : true
# একই নামের ভিডিওর সংঘর্ষ এড়াতে ভিডিও আইডি যুক্ত করবে

clear_downloaded_contents : true
# সার্ভার বন্ধ হলে বা রিস্টার্ট দিলে ডাউনলোড ফাইলগুলো মুছে ফেলবে (জায়গা বাঁচাতে)
